// Comprehensive Indian location database
export const INDIAN_LOCATIONS = [
  // ANDHRA PRADESH
  // Major Cities
  { name: "Visakhapatnam", state: "Andhra Pradesh", district: "Visakhapatnam", type: "city" },
  { name: "Vijayawada", state: "Andhra Pradesh", district: "Krishna", type: "city" },
  { name: "Guntur", state: "Andhra Pradesh", district: "Guntur", type: "city" },
  { name: "Nellore", state: "Andhra Pradesh", district: "Nellore", type: "city" },
  { name: "Kurnool", state: "Andhra Pradesh", district: "Kurnool", type: "city" },
  { name: "Tirupati", state: "Andhra Pradesh", district: "Chittoor", type: "city" },
  { name: "Anantapur", state: "Andhra Pradesh", district: "Anantapur", type: "city" },
  { name: "Kakinada", state: "Andhra Pradesh", district: "East Godavari", type: "city" },
  { name: "Eluru", state: "Andhra Pradesh", district: "West Godavari", type: "city" },
  { name: "Ongole", state: "Andhra Pradesh", district: "Prakasam", type: "city" },
  { name: "Nandyal", state: "Andhra Pradesh", district: "Kurnool", type: "city" },
  { name: "Machilipatnam", state: "Andhra Pradesh", district: "Krishna", type: "city" },
  { name: "Adoni", state: "Andhra Pradesh", district: "Kurnool", type: "city" },
  { name: "Chittoor", state: "Andhra Pradesh", district: "Chittoor", type: "city" },
  { name: "Anakapalle", state: "Andhra Pradesh", district: "Visakhapatnam", type: "city" },
  { name: "Tadepalligudem", state: "Andhra Pradesh", district: "West Godavari", type: "city" },
  { name: "Hindupur", state: "Andhra Pradesh", district: "Anantapur", type: "city" },
  { name: "Proddatur", state: "Andhra Pradesh", district: "YSR", type: "city" },
  { name: "Bhimavaram", state: "Andhra Pradesh", district: "West Godavari", type: "city" },
  { name: "Madanapalle", state: "Andhra Pradesh", district: "Chittoor", type: "city" },
  { name: "Guntakal", state: "Andhra Pradesh", district: "Anantapur", type: "city" },
  { name: "Markapur", state: "Andhra Pradesh", district: "Prakasam", type: "city" },
  { name: "Gudivada", state: "Andhra Pradesh", district: "Krishna", type: "city" },
  { name: "Srikakulam", state: "Andhra Pradesh", district: "Srikakulam", type: "city" },
  { name: "Bapatla", state: "Andhra Pradesh", district: "Bapatla", type: "city" },
  { name: "Narsapuram", state: "Andhra Pradesh", district: "West Godavari", type: "city" },
  { name: "Palakollu", state: "Andhra Pradesh", district: "West Godavari", type: "city" },
  { name: "Narsaraopet", state: "Andhra Pradesh", district: "Palnadu", type: "city" },
  { name: "Tadipatri", state: "Andhra Pradesh", district: "Anantapur", type: "city" },
  { name: "Chirala", state: "Andhra Pradesh", district: "Prakasam", type: "city" },
  { name: "Annavaram", state: "Andhra Pradesh", district: "East Godavari", type: "village" },
  { name: "Srisailam", state: "Andhra Pradesh", district: "Kurnool", type: "village" },
  { name: "Lepakshi", state: "Andhra Pradesh", district: "Anantapur", type: "village" },
  { name: "Amaravathi", state: "Andhra Pradesh", district: "Guntur", type: "village" },
  { name: "Rajam", state: "Andhra Pradesh", district: "Vizianagaram", type: "village" },
  { name: "Tekkali", state: "Andhra Pradesh", district: "Srikakulam", type: "village" },
  { name: "Parvathipuram", state: "Andhra Pradesh", district: "Vizianagaram", type: "village" },
  { name: "Salur", state: "Andhra Pradesh", district: "Vizianagaram", type: "village" },
  { name: "Bobbili", state: "Andhra Pradesh", district: "Vizianagaram", type: "village" },
  { name: "Cheepurupalli", state: "Andhra Pradesh", district: "Vizianagaram", type: "village" },
  { name: "Palasa", state: "Andhra Pradesh", district: "Srikakulam", type: "village" },
  { name: "Ichchapuram", state: "Andhra Pradesh", district: "Srikakulam", type: "village" },
  { name: "Pathapatnam", state: "Andhra Pradesh", district: "Srikakulam", type: "village" },
  { name: "Rangampeta", state: "Andhra Pradesh", district: "East Godavari", type: "village" },
  { name: "Pithapuram", state: "Andhra Pradesh", district: "East Godavari", type: "village" },
  { name: "Samalkot", state: "Andhra Pradesh", district: "East Godavari", type: "village" },
  { name: "Peddapuram", state: "Andhra Pradesh", district: "East Godavari", type: "village" },
  { name: "Mummidivaram", state: "Andhra Pradesh", district: "East Godavari", type: "village" },
  { name: "Amalapuram", state: "Andhra Pradesh", district: "East Godavari", type: "village" },
  { name: "Mandapeta", state: "Andhra Pradesh", district: "East Godavari", type: "village" },
  { name: "Gannavaram", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Vuyyuru", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Nuzvid", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Jaggayyapeta", state: "Andhra Pradesh", district: "NTR", type: "village" },
  { name: "Nandigama", state: "Andhra Pradesh", district: "NTR", type: "village" },
  { name: "Tiruvuru", state: "Andhra Pradesh", district: "NTR", type: "village" },
  { name: "Mylavaram", state: "Andhra Pradesh", district: "NTR", type: "village" },
  { name: "Vijayawada Rural", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Penamaluru", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Kankipadu", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Ibrahimpatnam", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Avanigadda", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Mopidevi", state: "Andhra Pradesh", district: "Krishna", type: "village" },
  { name: "Chandarlapadu", state: "Andhra Pradesh", district: "NTR", type: "village" },
  { name: "Vatsavai", state: "Andhra Pradesh", district: "NTR", type: "village" },
  { name: "Mandadam", state: "Andhra Pradesh", district: "Guntur", type: "village" },
  { name: "Tadikonda", state: "Andhra Pradesh", district: "Guntur", type: "village" },
  { name: "Pedakakani", state: "Andhra Pradesh", district: "Guntur", type: "village" },
  { name: "Mangalagiri", state: "Andhra Pradesh", district: "Guntur", type: "village" },
  { name: "Sattenapalle", state: "Andhra Pradesh", district: "Palnadu", type: "village" },
  { name: "Narsaraopet", state: "Andhra Pradesh", district: "Palnadu", type: "village" },
  { name: "Vinukonda", state: "Andhra Pradesh", district: "Palnadu", type: "village" },
  { name: "Ponnur", state: "Andhra Pradesh", district: "Guntur", type: "village" },
  { name: "Bapatla", state: "Andhra Pradesh", district: "Bapatla", type: "village" },
  { name: "Repalle", state: "Andhra Pradesh", district: "Bapatla", type: "village" },
  { name: "Chirala", state: "Andhra Pradesh", district: "Bapatla", type: "village" },
  { name: "Ongole", state: "Andhra Pradesh", district: "Prakasam", type: "village" },
  { name: "Markapuram", state: "Andhra Pradesh", district: "Prakasam", type: "village" },
  { name: "Kanigiri", state: "Andhra Pradesh", district: "Prakasam", type: "village" },
  { name: "Giddalur", state: "Andhra Pradesh", district: "Prakasam", type: "village" },
  { name: "Podili", state: "Andhra Pradesh", district: "Prakasam", type: "village" },
  { name: "Yerragondapalem", state: "Andhra Pradesh", district: "Prakasam", type: "village" },
  { name: "Cumbum", state: "Andhra Pradesh", district: "Prakasam", type: "village" },
  { name: "Rajampet", state: "Andhra Pradesh", district: "Annamaiah", type: "village" },
  { name: "Rayachoti", state: "Andhra Pradesh", district: "Annamaiah", type: "village" },
  { name: "Madanapalle", state: "Andhra Pradesh", district: "Annamaiah", type: "village" },
  { name: "Punganur", state: "Andhra Pradesh", district: "Annamaiah", type: "village" },
  { name: "Kalyandurg", state: "Andhra Pradesh", district: "Anantapur", type: "village" },
  { name: "Uravakonda", state: "Andhra Pradesh", district: "Anantapur", type: "village" },
  { name: "Guntakal", state: "Andhra Pradesh", district: "Anantapur", type: "village" },
  { name: "Gooty", state: "Andhra Pradesh", district: "Anantapur", type: "village" },
  { name: "Tadipatri", state: "Andhra Pradesh", district: "Anantapur", type: "village" },
  { name: "Dharmavaram", state: "Andhra Pradesh", district: "Sri Sathya Sai", type: "village" },
  { name: "Hindupur", state: "Andhra Pradesh", district: "Sri Sathya Sai", type: "village" },
  { name: "Puttaparthi", state: "Andhra Pradesh", district: "Sri Sathya Sai", type: "village" },
  { name: "Kadiri", state: "Andhra Pradesh", district: "Sri Sathya Sai", type: "village" },
  { name: "Madhira", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Khammam", state: "Telangana", district: "Khammam", type: "city" },
  { name: "Warangal", state: "Telangana", district: "Warangal", type: "city" },
  { name: "Karimnagar", state: "Telangana", district: "Karimnagar", type: "city" },
  { name: "Nizamabad", state: "Telangana", district: "Nizamabad", type: "city" },
  { name: "Medak", state: "Telangana", district: "Medak", type: "village" },
  { name: "Siddipet", state: "Telangana", district: "Medak", type: "village" },
  { name: "Sangareddy", state: "Telangana", district: "Sangareddy", type: "city" },
  { name: "Mahabubnagar", state: "Telangana", district: "Mahabubnagar", type: "city" },
  { name: "Nalgonda", state: "Telangana", district: "Nalgonda", type: "city" },
  { name: "Miryalaguda", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Bhongir", state: "Telangana", district: "Yadadri Bhuvanagiri", type: "village" },
  { name: "Jagtial", state: "Telangana", district: "Jagtial", type: "city" },
  { name: "Ramagundam", state: "Telangana", district: "Peddapalli", type: "city" },
  { name: "Mancherial", state: "Telangana", district: "Mancherial", type: "city" },
  { name: "Bellampalli", state: "Telangana", district: "Mancherial", type: "village" },
  { name: "Mandamarri", state: "Telangana", district: "Mancherial", type: "village" },
  { name: "Asifabad", state: "Telangana", district: "Kumram Bheem Asifabad", type: "village" },
  { name: "Kagaznagar", state: "Telangana", district: "Kumram Bheem Asifabad", type: "village" },
  { name: "Adilabad", state: "Telangana", district: "Adilabad", type: "city" },
  { name: "Nirmal", state: "Telangana", district: "Nirmal", type: "city" },
  { name: "Jangaon", state: "Telangana", district: "Jangaon", type: "village" },
  { name: "Suryapet", state: "Telangana", district: "Suryapet", type: "city" },
  { name: "Kothagudem", state: "Telangana", district: "Bhadradri Kothagudem", type: "city" },
  { name: "Palair", state: "Telangana", district: "Bhadradri Kothagudem", type: "village" },
  { name: "Wyra", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Tirumalayapalem", state: "Telangana", district: "Khammam", type: "village" },
  
  // TELANGANA VILLAGES AND TOWNS
  { name: "Achampet", state: "Telangana", district: "Nagarkurnool", type: "village" },
  { name: "Adilabad", state: "Telangana", district: "Adilabad", type: "village" },
  { name: "Aler", state: "Telangana", district: "Yadadri Bhuvanagiri", type: "village" },
  { name: "Amberpet", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Andole", state: "Telangana", district: "Sangareddy", type: "village" },
  { name: "Armoor", state: "Telangana", district: "Nizamabad", type: "village" },
  { name: "Aruku", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Asifabad", state: "Telangana", district: "Kumram Bheem Asifabad", type: "village" },
  { name: "Atmakur", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Bachannapet", state: "Telangana", district: "Yadadri Bhuvanagiri", type: "village" },
  { name: "Banswada", state: "Telangana", district: "Nizamabad", type: "village" },
  { name: "Barkas", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Begumpet", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Bhimavaram", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Bhongir", state: "Telangana", district: "Yadadri Bhuvanagiri", type: "village" },
  { name: "Bodhan", state: "Telangana", district: "Nizamabad", type: "village" },
  { name: "Chegunta", state: "Telangana", district: "Medak", type: "village" },
  { name: "Chevella", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Chilakaluripet", state: "Telangana", district: "Medak", type: "village" },
  { name: "Chintalapudi", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Chintapalli", state: "Telangana", district: "Adilabad", type: "village" },
  { name: "Chirala", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Cumbum", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Dachepalli", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Damaracherla", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Devarakonda", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Dharmavaram", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Divili", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Donakonda", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Duggondi", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Durgi", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Eluru", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Eturnagaram", state: "Telangana", district: "Jayashankar Bhupalapally", type: "village" },
  { name: "Gachibowli", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Gajwel", state: "Telangana", district: "Medak", type: "village" },
  { name: "Gandhari", state: "Telangana", district: "Nizamabad", type: "village" },
  { name: "Gandipet", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Gannavaram", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Garidepally", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Giddalur", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Gollapalli", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Gopalapuram", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Gopalpur", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Gorantla", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Gudur", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Gummadidala", state: "Telangana", district: "Medchal Malkajgiri", type: "village" },
  { name: "Gurramgonda", state: "Telangana", district: "Medchal Malkajgiri", type: "village" },
  { name: "Gurramkonda", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Himayatnagar", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Huzurnagar", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Huzurabad", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Ibrahimpatnam", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Ichchapuram", state: "Telangana", district: "Adilabad", type: "village" },
  { name: "Jaggayyapet", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Jagitial", state: "Telangana", district: "Jagtial", type: "village" },
  { name: "Jalpally", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Jangaon", state: "Telangana", district: "Jangaon", type: "village" },
  { name: "Jannaram", state: "Telangana", district: "Adilabad", type: "village" },
  { name: "Jinnaram", state: "Telangana", district: "Medak", type: "village" },
  { name: "Jogulamba", state: "Telangana", district: "Jogulamba Gadwal", type: "village" },
  { name: "Jurala", state: "Telangana", district: "Jogulamba Gadwal", type: "village" },
  { name: "Kalwakurthy", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Kamareddy", state: "Telangana", district: "Kamareddy", type: "village" },
  { name: "Kandukur", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Kanigiri", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Karepally", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Kashmirgadda", state: "Telangana", district: "Nizamabad", type: "village" },
  { name: "Kavali", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Kesamudram", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Khammam", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Kodad", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Kodakandla", state: "Telangana", district: "Jagtial", type: "village" },
  { name: "Kodangal", state: "Telangana", district: "Medak", type: "village" },
  { name: "Kondagatla", state: "Telangana", district: "Medak", type: "village" },
  { name: "Kondapur", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Kothagudem", state: "Telangana", district: "Bhadradri Kothagudem", type: "village" },
  { name: "Kothakota", state: "Telangana", district: "Wanaparthy", type: "village" },
  { name: "Kothapalli", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Kothur", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Kukatpally", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Kumaram", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Kummari", state: "Telangana", district: "Adilabad", type: "village" },
  { name: "Kundurg", state: "Telangana", district: "Nizamabad", type: "village" },
  { name: "Kurnool", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Lakshettipet", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Lalbahadur", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Lalapet", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Laxmipur", state: "Telangana", district: "Adilabad", type: "village" },
  { name: "Lingampalli", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Madhira", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Madhurawada", state: "Telangana", district: "Visakhapatnam", type: "village" },
  { name: "Mahabubabad", state: "Telangana", district: "Mahabubabad", type: "village" },
  { name: "Mahadevpur", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Maharani", state: "Telangana", district: "Adilabad", type: "village" },
  { name: "Mallapur", state: "Telangana", district: "Medchal Malkajgiri", type: "village" },
  { name: "Mandal", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Mandamarri", state: "Telangana", district: "Mancherial", type: "village" },
  { name: "Mandapeta", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Mancherial", state: "Telangana", district: "Mancherial", type: "village" },
  { name: "Mangalagiri", state: "Telangana", district: "Guntur", type: "village" },
  { name: "Manuguru", state: "Telangana", district: "Bhadradri Kothagudem", type: "village" },
  { name: "Maripeda", state: "Telangana", district: "Mahabubabad", type: "village" },
  { name: "Markapur", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Martur", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Medarmetla", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Medchal", state: "Telangana", district: "Medchal Malkajgiri", type: "village" },
  { name: "Medikonduru", state: "Telangana", district: "Guntur", type: "village" },
  { name: "Mellacheruvu", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Metpalli", state: "Telangana", district: "Jagtial", type: "village" },
  { name: "Mogullapalli", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Mothkur", state: "Telangana", district: "Yadadri Bhuvanagiri", type: "village" },
  { name: "Mudinepalli", state: "Telangana", district: "West Godavari", type: "village" },
  { name: "Mummidivaram", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Munagala", state: "Telangana", district: "Nellore", type: "village" },
  { name: "Muppalla", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Mylavaram", state: "Telangana", district: "NTR", type: "village" },
  { name: "Nagarjunasagar", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Nagarkurnool", state: "Telangana", district: "Nagarkurnool", type: "village" },
  { name: "Nakkapalli", state: "Telangana", district: "Visakhapatnam", type: "village" },
  { name: "Nalgonda", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Nallacheruvu", state: "Telangana", district: "Anantapur", type: "village" },
  { name: "Nallajerla", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Nallapadu", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Nampally", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Nandigama", state: "Telangana", district: "NTR", type: "village" },
  { name: "Nandikonda", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Nandivada", state: "Telangana", district: "Krishna", type: "village" },
  { name: "Narayankhed", state: "Telangana", district: "Medak", type: "village" },
  { name: "Narsampet", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Narsaraopet", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Narsapur", state: "Telangana", district: "West Godavari", type: "village" },
  { name: "Narsipatnam", state: "Telangana", district: "Visakhapatnam", type: "village" },
  { name: "Narayanpet", state: "Telangana", district: "Narayanpet", type: "village" },
  { name: "Narsapur", state: "Telangana", district: "West Godavari", type: "village" },
  { name: "Narsaraopet", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Narsipatnam", state: "Telangana", district: "Visakhapatnam", type: "village" },
  { name: "Nekkonda", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Nellikuduru", state: "Telangana", district: "Mahabubabad", type: "village" },
  { name: "Nemali", state: "Telangana", district: "Krishna", type: "village" },
  { name: "Nirmal", state: "Telangana", district: "Nirmal", type: "village" },
  { name: "Nizamabad", state: "Telangana", district: "Nizamabad", type: "village" },
  { name: "Nuzvid", state: "Telangana", district: "Krishna", type: "village" },
  { name: "Ongole", state: "Telangana", district: "Prakasam", type: "village" },
  { name: "Osmannagar", state: "Telangana", district: "Kamareddy", type: "village" },
  { name: "Paleru", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Palakonda", state: "Telangana", district: "Srikakulam", type: "village" },
  { name: "Palamaner", state: "Telangana", district: "Chittoor", type: "village" },
  { name: "Palasa", state: "Telangana", district: "Srikakulam", type: "village" },
  { name: "Parchur", state: "Telangana", district: "Bapatla", type: "village" },
  { name: "Parkal", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Parvathipuram", state: "Telangana", district: "Vizianagaram", type: "village" },
  { name: "Pasarla", state: "Telangana", district: "Anantapur", type: "village" },
  { name: "Patancheru", state: "Telangana", district: "Sangareddy", type: "village" },
  { name: "Pathapatnam", state: "Telangana", district: "Srikakulam", type: "village" },
  { name: "Peddapalli", state: "Telangana", district: "Peddapalli", type: "village" },
  { name: "Peddapuram", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Pegadapalli", state: "Telangana", district: "Peddapalli", type: "village" },
  { name: "Penukonda", state: "Telangana", district: "Sri Sathya Sai", type: "village" },
  { name: "Piduguralla", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Piler", state: "Telangana", district: "Chittoor", type: "village" },
  { name: "Pithapuram", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Podili", state: "Telangana", district: "Prakasam", type: "village" },
  { name: "Ponnur", state: "Telangana", district: "Guntur", type: "village" },
  { name: "Pothareddypally", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Prathipadu", state: "Telangana", district: "Guntur", type: "village" },
  { name: "Proddatur", state: "Telangana", district: "YSR", type: "village" },
  { name: "Pulicharla", state: "Telangana", district: "Chittoor", type: "village" },
  { name: "Pulivendula", state: "Telangana", district: "YSR", type: "village" },
  { name: "Punganur", state: "Telangana", district: "Chittoor", type: "village" },
  { name: "Puttaparthi", state: "Telangana", district: "Sri Sathya Sai", type: "village" },
  { name: "Rajahmundry", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Rajampet", state: "Telangana", district: "Annamaiah", type: "village" },
  { name: "Ramachandrapuram", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Ramagundam", state: "Telangana", district: "Peddapalli", type: "village" },
  { name: "Ramannapet", state: "Telangana", district: "Yadadri Bhuvanagiri", type: "village" },
  { name: "Rangareddy", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Rapur", state: "Telangana", district: "Nellore", type: "village" },
  { name: "Ravulapalem", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Rayachoti", state: "Telangana", district: "Annamaiah", type: "village" },
  { name: "Rayadurg", state: "Telangana", district: "Anantapur", type: "village" },
  { name: "Repalle", state: "Telangana", district: "Bapatla", type: "village" },
  { name: "Sadasivpet", state: "Telangana", district: "Sangareddy", type: "village" },
  { name: "Saidapur", state: "Telangana", district: "Karimnagar", type: "village" },
  { name: "Sailu", state: "Telangana", district: "Mahabubabad", type: "village" },
  { name: "Sainikpuri", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Sakleshpur", state: "Telangana", district: "Hassan", type: "village" },
  { name: "Salur", state: "Telangana", district: "Vizianagaram", type: "village" },
  { name: "Samalkot", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Sangareddy", state: "Telangana", district: "Sangareddy", type: "village" },
  { name: "Sathupalli", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Shadnagar", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Shamirpet", state: "Telangana", district: "Medchal Malkajgiri", type: "village" },
  { name: "Shankarpalli", state: "Telangana", district: "Ranga Reddy", type: "village" },
  { name: "Shanthinagar", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Shapur", state: "Telangana", district: "Medak", type: "village" },
  { name: "Shikarpur", state: "Telangana", district: "Guntur", type: "village" },
  { name: "Siddavattam", state: "Telangana", district: "YSR", type: "village" },
  { name: "Siddipet", state: "Telangana", district: "Medak", type: "village" },
  { name: "Singareni", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Sircilla", state: "Telangana", district: "Rajanna Sircilla", type: "village" },
  { name: "Somanahalli", state: "Telangana", district: "Bangalore Rural", type: "village" },
  { name: "Sompeta", state: "Telangana", district: "Srikakulam", type: "village" },
  { name: "Srinagar", state: "Telangana", district: "Visakhapatnam", type: "village" },
  { name: "Srinivasapur", state: "Telangana", district: "Chittoor", type: "village" },
  { name: "Srisailam", state: "Telangana", district: "Kurnool", type: "village" },
  { name: "Sullurpeta", state: "Telangana", district: "Nellore", type: "village" },
  { name: "Suryapet", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Tadepalligudem", state: "Telangana", district: "West Godavari", type: "village" },
  { name: "Tadikonda", state: "Telangana", district: "Guntur", type: "village" },
  { name: "Tadipatri", state: "Telangana", district: "Anantapur", type: "village" },
  { name: "Tandur", state: "Telangana", district: "Vikarabad", type: "village" },
  { name: "Tanuku", state: "Telangana", district: "West Godavari", type: "village" },
  { name: "Tekkali", state: "Telangana", district: "Srikakulam", type: "village" },
  { name: "Thalladi", state: "Telangana", district: "Mahabubabad", type: "village" },
  { name: "Thimmajipet", state: "Telangana", district: "Nagarkurnool", type: "village" },
  { name: "Thungaturthy", state: "Telangana", district: "Suryapet", type: "village" },
  { name: "Tirumala", state: "Telangana", district: "Chittoor", type: "village" },
  { name: "Tirupati", state: "Telangana", district: "Chittoor", type: "village" },
  { name: "Tirupathi", state: "Telangana", district: "Chittoor", type: "village" },
  { name: "Tiruvuru", state: "Telangana", district: "NTR", type: "village" },
  { name: "Uppal", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Uppugundur", state: "Telangana", district: "Guntur", type: "village" },
  { name: "Uravakonda", state: "Telangana", district: "Anantapur", type: "village" },
  { name: "Utnoor", state: "Telangana", district: "Adilabad", type: "village" },
  { name: "Vadapalli", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Vaidyanathpur", state: "Telangana", district: "Medak", type: "village" },
  { name: "Vaikuntapuram", state: "Telangana", district: "Nellore", type: "village" },
  { name: "Vanasthalipuram", state: "Telangana", district: "Hyderabad", type: "village" },
  { name: "Vangara", state: "Telangana", district: "Rajanna Sircilla", type: "village" },
  { name: "Vanguru", state: "Telangana", district: "Mahabubabad", type: "village" },
  { name: "Vemulawada", state: "Telangana", district: "Rajanna Sircilla", type: "village" },
  { name: "Vempalli", state: "Telangana", district: "YSR", type: "village" },
  { name: "Vijayapuri", state: "Telangana", district: "Nalgonda", type: "village" },
  { name: "Vinjamuru", state: "Telangana", district: "Nellore", type: "village" },
  { name: "Vinukonda", state: "Telangana", district: "Palnadu", type: "village" },
  { name: "Visakhapatnam", state: "Telangana", district: "Visakhapatnam", type: "village" },
  { name: "Vissannapeta", state: "Telangana", district: "East Godavari", type: "village" },
  { name: "Vizag", state: "Telangana", district: "Visakhapatnam", type: "village" },
  { name: "Vizianagaram", state: "Telangana", district: "Vizianagaram", type: "village" },
  { name: "Vuyyuru", state: "Telangana", district: "Krishna", type: "village" },
  { name: "Waddepalle", state: "Telangana", district: "Mahabubabad", type: "village" },
  { name: "Wanaparthy", state: "Telangana", district: "Wanaparthy", type: "village" },
  { name: "Warangal", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Wardhannapet", state: "Telangana", district: "Warangal", type: "village" },
  { name: "Yadagirigutta", state: "Telangana", district: "Yadadri Bhuvanagiri", type: "village" },
  { name: "Yellandu", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Yellareddy", state: "Telangana", district: "Kamareddy", type: "village" },
  { name: "Yerragondapalem", state: "Telangana", district: "Prakasam", type: "village" },
  { name: "Yerrupalem", state: "Telangana", district: "Khammam", type: "village" },
  { name: "Zahirabad", state: "Telangana", district: "Sangareddy", type: "village" },
  
  // KARNATAKA
  // Major Cities
  { name: "Bangalore", state: "Karnataka", district: "Bangalore Urban", type: "city" },
  { name: "Mysore", state: "Karnataka", district: "Mysore", type: "city" },
  { name: "Hubli", state: "Karnataka", district: "Dharwad", type: "city" },
  { name: "Dharwad", state: "Karnataka", district: "Dharwad", type: "city" },
  { name: "Mangalore", state: "Karnataka", district: "Dakshina Kannada", type: "city" },
  { name: "Belgaum", state: "Karnataka", district: "Belagavi", type: "city" },
  { name: "Gulbarga", state: "Karnataka", district: "Kalaburagi", type: "city" },
  { name: "Bellary", state: "Karnataka", district: "Ballari", type: "city" },
  { name: "Bijapur", state: "Karnataka", district: "Vijayapura", type: "city" },
  { name: "Shimoga", state: "Karnataka", district: "Shivamogga", type: "city" },
  { name: "Tumkur", state: "Karnataka", district: "Tumakuru", type: "city" },
  { name: "Raichur", state: "Karnataka", district: "Raichur", type: "city" },
  { name: "Davangere", state: "Karnataka", district: "Davanagere", type: "city" },
  { name: "Kolar", state: "Karnataka", district: "Kolar", type: "city" },
  { name: "Chitradurga", state: "Karnataka", district: "Chitradurga", type: "city" },
  { name: "Hassan", state: "Karnataka", district: "Hassan", type: "city" },
  { name: "Mandya", state: "Karnataka", district: "Mandya", type: "city" },
  { name: "Udupi", state: "Karnataka", district: "Udupi", type: "city" },
  { name: "Chikmagalur", state: "Karnataka", district: "Chikmagalur", type: "city" },
  { name: "Koppal", state: "Karnataka", district: "Koppal", type: "city" },
  { name: "Bagalkot", state: "Karnataka", district: "Bagalkot", type: "city" },
  { name: "Gadag", state: "Karnataka", district: "Gadag", type: "city" },
  { name: "Haveri", state: "Karnataka", district: "Haveri", type: "city" },
  { name: "Yadgir", state: "Karnataka", district: "Yadgir", type: "city" },
  { name: "Chamrajnagar", state: "Karnataka", district: "Chamarajanagar", type: "city" },
  { name: "Uttara Kannada", state: "Karnataka", district: "Uttara Kannada", type: "city" },
  { name: "Ramanagara", state: "Karnataka", district: "Ramanagara", type: "city" },
  { name: "Chikballapur", state: "Karnataka", district: "Chikballapur", type: "city" },
  { name: "Bangalore Rural", state: "Karnataka", district: "Bangalore Rural", type: "city" },
  
  // MAHARASHTRA
  // Major Cities
  { name: "Mumbai", state: "Maharashtra", district: "Mumbai City", type: "city" },
  { name: "Pune", state: "Maharashtra", district: "Pune", type: "city" },
  { name: "Nagpur", state: "Maharashtra", district: "Nagpur", type: "city" },
  { name: "Thane", state: "Maharashtra", district: "Thane", type: "city" },
  { name: "Nashik", state: "Maharashtra", district: "Nashik", type: "city" },
  { name: "Aurangabad", state: "Maharashtra", district: "Aurangabad", type: "city" },
  { name: "Solapur", state: "Maharashtra", district: "Solapur", type: "city" },
  { name: "Amravati", state: "Maharashtra", district: "Amravati", type: "city" },
  { name: "Nanded", state: "Maharashtra", district: "Nanded", type: "city" },
  { name: "Sangli", state: "Maharashtra", district: "Sangli", type: "city" },
  { name: "Kolhapur", state: "Maharashtra", district: "Kolhapur", type: "city" },
  { name: "Latur", state: "Maharashtra", district: "Latur", type: "city" },
  { name: "Dhule", state: "Maharashtra", district: "Dhule", type: "city" },
  { name: "Jalgaon", state: "Maharashtra", district: "Jalgaon", type: "city" },
  { name: "Ahmednagar", state: "Maharashtra", district: "Ahmednagar", type: "city" },
  { name: "Akola", state: "Maharashtra", district: "Akola", type: "city" },
  { name: "Chandrapur", state: "Maharashtra", district: "Chandrapur", type: "city" },
  { name: "Parbhani", state: "Maharashtra", district: "Parbhani", type: "city" },
  { name: "Yavatmal", state: "Maharashtra", district: "Yavatmal", type: "city" },
  { name: "Buldhana", state: "Maharashtra", district: "Buldhana", type: "city" },
  { name: "Wardha", state: "Maharashtra", district: "Wardha", type: "city" },
  { name: "Gondia", state: "Maharashtra", district: "Gondia", type: "city" },
  { name: "Gadchiroli", state: "Maharashtra", district: "Gadchiroli", type: "city" },
  { name: "Hingoli", state: "Maharashtra", district: "Hingoli", type: "city" },
  { name: "Jalna", state: "Maharashtra", district: "Jalna", type: "city" },
  { name: "Osmanabad", state: "Maharashtra", district: "Osmanabad", type: "city" },
  { name: "Nandurbar", state: "Maharashtra", district: "Nandurbar", type: "city" },
  { name: "Satara", state: "Maharashtra", district: "Satara", type: "city" },
  { name: "Ratnagiri", state: "Maharashtra", district: "Ratnagiri", type: "city" },
  { name: "Sindhudurg", state: "Maharashtra", district: "Sindhudurg", type: "city" },
  { name: "Raigad", state: "Maharashtra", district: "Raigad", type: "city" },
  { name: "Palghar", state: "Maharashtra", district: "Palghar", type: "city" },
  
  // TAMIL NADU
  // Major Cities
  { name: "Chennai", state: "Tamil Nadu", district: "Chennai", type: "city" },
  { name: "Coimbatore", state: "Tamil Nadu", district: "Coimbatore", type: "city" },
  { name: "Madurai", state: "Tamil Nadu", district: "Madurai", type: "city" },
  { name: "Tiruchirappalli", state: "Tamil Nadu", district: "Tiruchirappalli", type: "city" },
  { name: "Salem", state: "Tamil Nadu", district: "Salem", type: "city" },
  { name: "Tirunelveli", state: "Tamil Nadu", district: "Tirunelveli", type: "city" },
  { name: "Tiruppur", state: "Tamil Nadu", district: "Tiruppur", type: "city" },
  { name: "Vellore", state: "Tamil Nadu", district: "Vellore", type: "city" },
  { name: "Erode", state: "Tamil Nadu", district: "Erode", type: "city" },
  { name: "Thoothukudi", state: "Tamil Nadu", district: "Thoothukudi", type: "city" },
  { name: "Dindigul", state: "Tamil Nadu", district: "Dindigul", type: "city" },
  { name: "Thanjavur", state: "Tamil Nadu", district: "Thanjavur", type: "city" },
  { name: "Ranipet", state: "Tamil Nadu", district: "Vellore", type: "city" },
  { name: "Sivakasi", state: "Tamil Nadu", district: "Virudhunagar", type: "city" },
  { name: "Karur", state: "Tamil Nadu", district: "Karur", type: "city" },
  { name: "Kanchipuram", state: "Tamil Nadu", district: "Kanchipuram", type: "city" },
  { name: "Kumbakonam", state: "Tamil Nadu", district: "Thanjavur", type: "city" },
  { name: "Cuddalore", state: "Tamil Nadu", district: "Cuddalore", type: "city" },
  { name: "Kanyakumari", state: "Tamil Nadu", district: "Kanyakumari", type: "city" },
  { name: "Nagapattinam", state: "Tamil Nadu", district: "Nagapattinam", type: "city" },
  { name: "Tiruvannamalai", state: "Tamil Nadu", district: "Tiruvannamalai", type: "city" },
  { name: "Tirupathur", state: "Tamil Nadu", district: "Tirupathur", type: "city" },
  { name: "Pudukkottai", state: "Tamil Nadu", district: "Pudukkottai", type: "city" },
  { name: "Ramanathapuram", state: "Tamil Nadu", district: "Ramanathapuram", type: "city" },
  { name: "Namakkal", state: "Tamil Nadu", district: "Namakkal", type: "city" },
  { name: "Perambalur", state: "Tamil Nadu", district: "Perambalur", type: "city" },
  { name: "Villupuram", state: "Tamil Nadu", district: "Villupuram", type: "city" },
  { name: "Virudhunagar", state: "Tamil Nadu", district: "Virudhunagar", type: "city" },
  { name: "Ariyalur", state: "Tamil Nadu", district: "Ariyalur", type: "city" },
  { name: "Krishnagiri", state: "Tamil Nadu", district: "Krishnagiri", type: "city" },
  { name: "Tiruvarur", state: "Tamil Nadu", district: "Tiruvarur", type: "city" },
  { name: "Dharmapuri", state: "Tamil Nadu", district: "Dharmapuri", type: "city" },
  { name: "Theni", state: "Tamil Nadu", district: "Theni", type: "city" },
  { name: "Nilgiris", state: "Tamil Nadu", district: "Nilgiris", type: "city" },
  { name: "Chengalpattu", state: "Tamil Nadu", district: "Chengalpattu", type: "city" },
  { name: "Tiruvallur", state: "Tamil Nadu", district: "Tiruvallur", type: "city" },
  { name: "Chennai Rural", state: "Tamil Nadu", district: "Chennai", type: "city" },
  
  // UTTAR PRADESH
  // Major Cities
  { name: "Lucknow", state: "Uttar Pradesh", district: "Lucknow", type: "city" },
  { name: "Kanpur", state: "Uttar Pradesh", district: "Kanpur Nagar", type: "city" },
  { name: "Ghaziabad", state: "Uttar Pradesh", district: "Ghaziabad", type: "city" },
  { name: "Agra", state: "Uttar Pradesh", district: "Agra", type: "city" },
  { name: "Varanasi", state: "Uttar Pradesh", district: "Varanasi", type: "city" },
  { name: "Meerut", state: "Uttar Pradesh", district: "Meerut", type: "city" },
  { name: "Allahabad", state: "Uttar Pradesh", district: "Prayagraj", type: "city" },
  { name: "Bareilly", state: "Uttar Pradesh", district: "Bareilly", type: "city" },
  { name: "Aligarh", state: "Uttar Pradesh", district: "Aligarh", type: "city" },
  { name: "Moradabad", state: "Uttar Pradesh", district: "Moradabad", type: "city" },
  { name: "Saharanpur", state: "Uttar Pradesh", district: "Saharanpur", type: "city" },
  { name: "Noida", state: "Uttar Pradesh", district: "Gautam Buddha Nagar", type: "city" },
  { name: "Gurgaon", state: "Haryana", district: "Gurgaon", type: "city" },
  { name: "Faridabad", state: "Haryana", district: "Faridabad", type: "city" },
  { name: "Gwalior", state: "Madhya Pradesh", district: "Gwalior", type: "city" },
  { name: "Indore", state: "Madhya Pradesh", district: "Indore", type: "city" },
  { name: "Bhopal", state: "Madhya Pradesh", district: "Bhopal", type: "city" },
  { name: "Jabalpur", state: "Madhya Pradesh", district: "Jabalpur", type: "city" },
  { name: "Ujjain", state: "Madhya Pradesh", district: "Ujjain", type: "city" },
  { name: "Guna", state: "Madhya Pradesh", district: "Guna", type: "city" },
  { name: "Sagar", state: "Madhya Pradesh", district: "Sagar", type: "city" },
  { name: "Dewas", state: "Madhya Pradesh", district: "Dewas", type: "city" },
  { name: "Satna", state: "Madhya Pradesh", district: "Satna", type: "city" },
  { name: "Ratlam", state: "Madhya Pradesh", district: "Ratlam", type: "city" },
  { name: "Rewa", state: "Madhya Pradesh", district: "Rewa", type: "city" },
  { name: "Singrauli", state: "Madhya Pradesh", district: "Singrauli", type: "city" },
  { name: "Vidisha", state: "Madhya Pradesh", district: "Vidisha", type: "city" },
  { name: "Khargone", state: "Madhya Pradesh", district: "Khargone", type: "city" },
  { name: "Ashoknagar", state: "Madhya Pradesh", district: "Ashoknagar", type: "city" },
  { name: "Shivpuri", state: "Madhya Pradesh", district: "Shivpuri", type: "city" },
  { name: "Mandsaur", state: "Madhya Pradesh", district: "Mandsaur", type: "city" },
  { name: "Neemuch", state: "Madhya Pradesh", district: "Neemuch", type: "city" },
  { name: "Betul", state: "Madhya Pradesh", district: "Betul", type: "city" },
  { name: "Chhindwara", state: "Madhya Pradesh", district: "Chhindwara", type: "city" },
  { name: "Seoni", state: "Madhya Pradesh", district: "Seoni", type: "city" },
  { name: "Balaghat", state: "Madhya Pradesh", district: "Balaghat", type: "city" },
  { name: "Mandla", state: "Madhya Pradesh", district: "Mandla", type: "city" },
  { name: "Dindori", state: "Madhya Pradesh", district: "Dindori", type: "city" },
  { name: "Umaria", state: "Madhya Pradesh", district: "Umaria", type: "city" },
  { name: "Anuppur", state: "Madhya Pradesh", district: "Anuppur", type: "city" },
  { name: "Sheopur", state: "Madhya Pradesh", district: "Sheopur", type: "city" },
  { name: "Katni", state: "Madhya Pradesh", district: "Katni", type: "city" },
  { name: "Panna", state: "Madhya Pradesh", district: "Panna", type: "city" },
  { name: "Damoh", state: "Madhya Pradesh", district: "Damoh", type: "city" },
  { name: "Tikamgarh", state: "Madhya Pradesh", district: "Tikamgarh", type: "city" },
  { name: "Chhatarpur", state: "Madhya Pradesh", district: "Chhatarpur", type: "city" },
  { name: "Niwari", state: "Madhya Pradesh", district: "Niwari", type: "city" },
  { name: "Alirajpur", state: "Madhya Pradesh", district: "Alirajpur", type: "city" },
  { name: "Burhanpur", state: "Madhya Pradesh", district: "Burhanpur", type: "city" },
  { name: "Khandwa", state: "Madhya Pradesh", district: "Khandwa", type: "city" },
  { name: "Harda", state: "Madhya Pradesh", district: "Harda", type: "city" },
  { name: "Hoshangabad", state: "Madhya Pradesh", district: "Narmadapuram", type: "city" },
  
  // GUJARAT
  // Major Cities
  { name: "Ahmedabad", state: "Gujarat", district: "Ahmedabad", type: "city" },
  { name: "Surat", state: "Gujarat", district: "Surat", type: "city" },
  { name: "Vadodara", state: "Gujarat", district: "Vadodara", type: "city" },
  { name: "Rajkot", state: "Gujarat", district: "Rajkot", type: "city" },
  { name: "Bhavnagar", state: "Gujarat", district: "Bhavnagar", type: "city" },
  { name: "Jamnagar", state: "Gujarat", district: "Jamnagar", type: "city" },
  { name: "Junagadh", state: "Gujarat", district: "Junagadh", type: "city" },
  { name: "Gandhinagar", state: "Gujarat", district: "Gandhinagar", type: "city" },
  { name: "Anand", state: "Gujarat", district: "Anand", type: "city" },
  { name: "Nadiad", state: "Gujarat", district: "Kheda", type: "city" },
  { name: "Mehsana", state: "Gujarat", district: "Mehsana", type: "city" },
  { name: "Surendranagar", state: "Gujarat", district: "Surendranagar", type: "city" },
  { name: "Bharuch", state: "Gujarat", district: "Bharuch", type: "city" },
  { name: "Patan", state: "Gujarat", district: "Patan", type: "city" },
  { name: "Amreli", state: "Gujarat", district: "Amreli", type: "city" },
  { name: "Botad", state: "Gujarat", district: "Botad", type: "city" },
  { name: "Gir Somnath", state: "Gujarat", district: "Gir Somnath", type: "city" },
  { name: "Devbhumi Dwarka", state: "Gujarat", district: "Devbhumi Dwarka", type: "city" },
  { name: "Morbi", state: "Gujarat", district: "Morbi", type: "city" },
  { name: "Tapi", state: "Gujarat", district: "Tapi", type: "city" },
  { name: "Dang", state: "Gujarat", district: "Dang", type: "city" },
  { name: "Aravalli", state: "Gujarat", district: "Aravalli", type: "city" },
  { name: "Mahisagar", state: "Gujarat", district: "Mahisagar", type: "city" },
  { name: "Chhota Udepur", state: "Gujarat", district: "Chhota Udepur", type: "city" },
  { name: "Sabarkantha", state: "Gujarat", district: "Sabarkantha", type: "city" },
  { name: "Panchmahal", state: "Gujarat", district: "Panchmahal", type: "city" },
  { name: "Kheda", state: "Gujarat", district: "Kheda", type: "city" },
  { name: "Valsad", state: "Gujarat", district: "Valsad", type: "city" },
  { name: "Navsari", state: "Gujarat", district: "Navsari", type: "city" },
  { name: "Dahod", state: "Gujarat", district: "Dahod", type: "city" },
  { name: "Panchmahal", state: "Gujarat", district: "Panchmahal", type: "city" },
  
  // RAJASTHAN
  // Major Cities
  { name: "Jaipur", state: "Rajasthan", district: "Jaipur", type: "city" },
  { name: "Jodhpur", state: "Rajasthan", district: "Jodhpur", type: "city" },
  { name: "Kota", state: "Rajasthan", district: "Kota", type: "city" },
  { name: "Bikaner", state: "Rajasthan", district: "Bikaner", type: "city" },
  { name: "Udaipur", state: "Rajasthan", district: "Udaipur", type: "city" },
  { name: "Ajmer", state: "Rajasthan", district: "Ajmer", type: "city" },
  { name: "Bhilwara", state: "Rajasthan", district: "Bhilwara", type: "city" },
  { name: "Alwar", state: "Rajasthan", district: "Alwar", type: "city" },
  { name: "Bharatpur", state: "Rajasthan", district: "Bharatpur", type: "city" },
  { name: "Sikar", state: "Rajasthan", district: "Sikar", type: "city" },
  { name: "Sriganganagar", state: "Rajasthan", district: "Sriganganagar", type: "city" },
  { name: "Pali", state: "Rajasthan", district: "Pali", type: "city" },
  { name: "Nagaur", state: "Rajasthan", district: "Nagaur", type: "city" },
  { name: "Rajsamand", state: "Rajasthan", district: "Rajsamand", type: "city" },
  { name: "Tonk", state: "Rajasthan", district: "Tonk", type: "city" },
  { name: "Bundi", state: "Rajasthan", district: "Bundi", type: "city" },
  { name: "Dholpur", state: "Rajasthan", district: "Dholpur", type: "city" },
  { name: "Karauli", state: "Rajasthan", district: "Karauli", type: "city" },
  { name: "Sawai Madhopur", state: "Rajasthan", district: "Sawai Madhopur", type: "city" },
  { name: "Dausa", state: "Rajasthan", district: "Dausa", type: "city" },
  { name: "Churu", state: "Rajasthan", district: "Churu", type: "city" },
  { name: "Jhunjhunu", state: "Rajasthan", district: "Jhunjhunu", type: "city" },
  { name: "Hanumangarh", state: "Rajasthan", district: "Hanumangarh", type: "city" },
  { name: "Ganganagar", state: "Rajasthan", district: "Sriganganagar", type: "city" },
  { name: "Jaisalmer", state: "Rajasthan", district: "Jaisalmer", type: "city" },
  { name: "Barmer", state: "Rajasthan", district: "Barmer", type: "city" },
  { name: "Jalore", state: "Rajasthan", district: "Jalore", type: "city" },
  { name: "Pratapgarh", state: "Rajasthan", district: "Pratapgarh", type: "city" },
  { name: "Uttar Pradesh", state: "Uttar Pradesh", district: "Uttar Pradesh", type: "city" },
  { name: "Rajasthan", state: "Rajasthan", district: "Rajasthan", type: "city" },
  { name: "Madhya Pradesh", state: "Madhya Pradesh", district: "Madhya Pradesh", type: "city" },
  { name: "Tamil Nadu", state: "Tamil Nadu", district: "Tamil Nadu", type: "city" },
  { name: "Karnataka", state: "Karnataka", district: "Karnataka", type: "city" },
  { name: "Maharashtra", state: "Maharashtra", district: "Maharashtra", type: "city" },
  { name: "Andhra Pradesh", state: "Andhra Pradesh", district: "Andhra Pradesh", type: "city" },
  { name: "Telangana", state: "Telangana", district: "Telangana", type: "city" },
  { name: "Gujarat", state: "Gujarat", district: "Gujarat", type: "city" },
  { name: "West Bengal", state: "West Bengal", district: "West Bengal", type: "city" },
  { name: "Bihar", state: "Bihar", district: "Bihar", type: "city" },
  { name: "Odisha", state: "Odisha", district: "Odisha", type: "city" },
  { name: "Punjab", state: "Punjab", district: "Punjab", type: "city" },
  { name: "Haryana", state: "Haryana", district: "Haryana", type: "city" },
  { name: "Jammu and Kashmir", state: "Jammu and Kashmir", district: "Jammu and Kashmir", type: "city" },
  { name: "Himachal Pradesh", state: "Himachal Pradesh", district: "Himachal Pradesh", type: "city" },
  { name: "Uttarakhand", state: "Uttarakhand", district: "Uttarakhand", type: "city" },
  { name: "Kerala", state: "Kerala", district: "Kerala", type: "city" },
  { name: "Goa", state: "Goa", district: "Goa", type: "city" },
  { name: "Assam", state: "Assam", district: "Assam", type: "city" },
  { name: "Meghalaya", state: "Meghalaya", district: "Meghalaya", type: "city" },
  { name: "Manipur", state: "Manipur", district: "Manipur", type: "city" },
  { name: "Mizoram", state: "Mizoram", district: "Mizoram", type: "city" },
  { name: "Nagaland", state: "Nagaland", district: "Nagaland", type: "city" },
  { name: "Tripura", state: "Tripura", district: "Tripura", type: "city" },
  { name: "Sikkim", state: "Sikkim", district: "Sikkim", type: "city" },
  { name: "Andaman and Nicobar Islands", state: "Andaman and Nicobar Islands", district: "Andaman and Nicobar Islands", type: "city" },
  { name: "Lakshadweep", state: "Lakshadweep", district: "Lakshadweep", type: "city" },
  { name: "Puducherry", state: "Puducherry", district: "Puducherry", type: "city" },
  { name: "Delhi", state: "Delhi", district: "Delhi", type: "city" },
  { name: "Chandigarh", state: "Chandigarh", district: "Chandigarh", type: "city" },
];
